	<!-- footer starts here -->	
	<div id="footer-outer" class="clear"><div id="footer-wrap">
	
		<div class="col-a">
		
			<h3>Browse Licenses</h3>
			<div class="footer-list">
			  <ul>
				<li><a href="license-list.php?cat=all">All licenses</a></li>
				<li><a href="license-list.php?cat=data">Data licenses</a></li>
				<li><a href="license-list.php?cat=software">Software licenses</a></li>
				<li><a href="license-list.php?cat=content">Content licenses</a></li>
				<li><a href="license-list.php?cat=international">International licenses</a></li>
				<li><a href="license-list.php?cat=Canadian">Canadian licenses</a></li>
			  </ul>		
			</div>
			
			<h3>Contribute</h3>
			
			<p>Want to help expand CLIP's database of licensing information? Spot an error in one of the licenses?
			You can add a new license or edit an existing one with our user-friendly
			<a href="../tools/license_editor">license editor</a>.
			<p>Simply fill out the license editor form and then copy the generated JSON data. You can either
			<a href="mailto:kmewhort@cippic.ca">e-mail us the data</a>, or, preferably, directly submit your
			updates to our <a href="http://github.com/kmewhort/clip">GitHub repository</a>.</p>
				
		</div>
		
		<div class="col-a">
		
			<h3>Other Resources</h3>
			<p>We recommend the following resources for further informtion on open licenses:</p>
			<div class="footer-list">
				<ul>				
					<li><a href="http://www.cippic.ca/open-licensing">CIPPIC Open Licensing Project</a></li>
					<li><a href="http://opendefinition.org/">The Open Definition</a></li>
					<li><a href="http://okfn.org/">Open Knowledge Foundation</a></li>
					<li><a href="http://www.creativecommons.org">Creative Commons</a></li>		
				</ul>
			</div>
				
		</div>		
	
		<div class="col-b">
		
			<h3>About CLIP</h3>			
			
			<p><a href="http://www.cippic.ca"><img src="images/cippic-small.png" class="float-left" /></a>
			The CIPPIC Open Licensing Project (CLIP) is an initiative of the <a href="http://www.cippic.ca">Samuelson-Glushko Canadian Internet Policy and Public
			Interest Clinic</a>, a public interest technology law clinic at the Faculty of Law, Common Law Section, University of Ottawa.<br />This is a <em>beta</em> version of the project. The information may contain errors.  We will also be adding additional licenses and new features in the future!</p>
			
			<p><a href="http://geoconnections.nrcan.gc.ca/"><img src="images/geoconnections-small.png" class="float-left" /></a>
			Financial support for the project provided by <a href="http://geoconnections.nrcan.gc.ca/">GeoConnections</a>, a national collaborative initiative
			led by National Resources Canada.</p><p>GeoConnections supports the integration and use of Canadian Geospatial
			Data Infrastructure (CGDI), an on-line resource that improves the sharing, access and use of open
			geospatial information.</p>		
			
		</div>		
	
	<!-- footer ends -->		
	</div></div>
	
	<!-- footer-bottom starts -->		
	<div id="footer-bottom">
		<div class="bottom-left">
			<p>
			&copy; 2012 <strong><a href="http://www.cippic.ca">CIPPIC</a></strong>&nbsp; &nbsp; &nbsp;
			Design by <a href="http://www.cippic.ca">CIPPIC</a> and <a href="http://www.styleshout.com/">styleshout</a>.
			</p>
		</div>

	<!-- footer-bottom ends -->		
	</div>