<title>CLIP</title>
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
<meta name="author" content="cippic42" />
<meta name="description" content="CIPPIC Licence Information Project" />
<meta name="keywords" content="open licensing,open data,open source software,free software,software licenses,data licenses" />
<meta name="robots" content="index, follow" />
<link rel="stylesheet" type="text/css" media="screen" href="css/screen.css" />
