development:
  adapter: postgresql
  encoding: utf8
  database: clip_development
  pool: 5
  username: clip
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: clip_production
  pool: 5
  username: clip
  password: